[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "mazegen-v"
version = "1.0.0"
description = "Reusable Maze Generator Module for 42 School"
authors = [{ name = "V" }]
readme = "README.md"
requires-python = ">=3.10"
dependencies = []

[tool.setuptools.packages.find]
where = ["."]
include = ["mazegen*"]